/**
 * Auth Repository
 *
 * Single point of contact between the auth module and the database.
 * No business logic here — only data access.
 * The service layer owns all decisions; this layer owns all queries.
 *
 * Architecture note:
 *   The schema has no RefreshToken or PasswordResetToken table.
 *   - Refresh tokens are stateless JWTs (verified by signature).
 *   - Password reset tokens are generated by the service and returned
 *     for the caller to deliver via email. The schema must be extended
 *     with a PasswordResetToken model to support server-side validation
 *     in a future phase.
 */

import type { PrismaClient } from '@prisma/client';
import type { AuthUserRecord } from '../types/auth.types';

export class AuthRepository {
  constructor(private readonly prisma: PrismaClient) {}

  /**
   * Finds a user by email address for authentication.
   * Returns null when the user does not exist.
   */
  async findUserByEmail(email: string): Promise<AuthUserRecord | null> {
    const user = await this.prisma.user.findUnique({
      where: { email },
      select: {
        id:             true,
        email:          true,
        passwordHash:   true,
        organizationId: true,
        status:         true,
        firstName:      true,
        lastName:       true,
      },
    });

    return user;
  }

  /**
   * Finds a user by ID for token verification and refresh flows.
   * Returns null when the user does not exist.
   */
  async findUserById(id: string): Promise<AuthUserRecord | null> {
    const user = await this.prisma.user.findUnique({
      where: { id },
      select: {
        id:             true,
        email:          true,
        passwordHash:   true,
        organizationId: true,
        status:         true,
        firstName:      true,
        lastName:       true,
      },
    });

    return user;
  }

  /**
   * Updates the passwordHash for a user.
   * Used by changePassword and resetPassword flows.
   */
  async updatePassword(userId: string, passwordHash: string): Promise<void> {
    await this.prisma.user.update({
      where: { id: userId },
      data:  { passwordHash },
    });
  }
}
